kata-containers/osbuilder

- rootfs-builder/rootfs.sh
If for some reason the GOPATH variable is not set
in the shell the script should exit instead of continuing the execution. 
> Exit if GOPATH is not set

- rootfs-builder/fedora/Dockerfile
- rootfs-builder/fedora/rootfs_lib.sh
Changed rootfs-builder/fedora/rootfs_lib.sh to select
repo URL based on arch.
Fixes #21.
> scripts: Arch dependent repo url for fedora

- image-builder/README.md
The `image_builder.sh` script must be run as `root`.
Fixes #36.
> docs: Fix image builder instructions.

- .ci/lib.sh
- .ci/setup.sh
- .ci/static-checks.sh
Require all PRs to contain a "Fixes #XXX" comment and a
"Signed-off-by:" comment.
Also necessitated adding a very minimal `.travis.yml` to
trigger `checkcommits`.
Fixes #12.
> CI: Enable checkcommits

- image-builder/image_builder.sh
Changed image-builder/image_builder.sh to
automatically calculate the size of the root disk
Fixes #25.
1. Calculate the initial size of the raw disk space
by adding 30% buffer in calculated rootfs size
2. Layover partition and file system structures 
on raw disk
3. Check if the available size is greater than
rootfs size
4. If not, add 5% in the extra buffer and go to step 1. 
> scripts: Add an "auto-size" feature

- .travis.yml
- Makefile
- README.md
- image-builder/image_builder.sh
- initrd-builder/README.md
- initrd-builder/initrd_builder.sh
- rootfs-builder/README.md
- rootfs-builder/centos/config.sh
- rootfs-builder/centos/rootfs_lib.sh
- rootfs-builder/clearlinux/config.sh
- rootfs-builder/euleros/config.sh
- rootfs-builder/fedora/config.sh
- rootfs-builder/rootfs.sh
- tests/image_creation.bats
The kata agent can be used as init process and thus we do not always rely on systemd. Also created kata initrd image based on rootfs created by `rootfs.sh`.
fixes: #5 
fixes: #7
> Allow to use agent as init process and create initrd image based on rootfs

- image-builder/image_builder.sh
- initrd-builder/initrd_builder.sh
- rootfs-builder/alpine/Dockerfile.in
- rootfs-builder/alpine/config.sh
- rootfs-builder/alpine/rootfs_lib.sh
- rootfs-builder/rootfs.sh
- tests/image_creation.bats
This PR adds alpine rootfs support so that we can get much smaller rootfs image and initrd image.
For example, I got 8.5MB kata-initrd.img with alpine rootfs in contrast of 50+MB centos rootfs.
This is based on top of #49 and I'll rebase once that one gets merged.
> alpine rootfs support

- image-builder/image_builder.sh
When user manually specifies root disk image
size the value should be greater than 0.
Fixes : #57
> scripts : handle 0 and negative root disk sizes

- image-builder/image_builder.sh
There is no way to specify the remaining free space of the root partition.
It can vary depending on the upper bound size of the image aligned to 128MB
and the size of the root filesystem.
The following patch allow the user to specify that at least a certain amount
of space (defined in MB) will be kept in the partition.
Fixes: #45
> image-builder: Allow to specify root partition free space

- rootfs-builder/rootfs.sh
Install the right version of golang depending of the host architecture
fixes #60
> rootfs-builder: ARM64 support

- tests/image_creation.bats
Fixes #46.
Signed-off-by: Liang Chenye <liangchenye@huawei.com>
> skip euleros build due to timeout reason

- .ci/setup.sh
Run the `.ci/setup.sh` script with `set -e` to ensure all failures are
fatal.
Fixes #65.
> CI: Make setup script fail on error

- Makefile
- initrd-builder/initrd_builder.sh
Just so that we do not have to re-build rootfs every time for local build/testing.
> allow to build image and initrd based on existing rootfs

- rootfs-builder/rootfs.sh
Install the right golang binaries for ppc64le
Fixes #72
> Install the right golang binaries for ppc64le

- initrd-builder/initrd_builder.sh
The initrd image name should be kata-containers-initrd.img, as its referenced by this name later on.
> initrd-builder: fix initrd image name

- .ci/setup.sh
- Makefile
- VERSION
- image-builder/image_builder.sh
- initrd-builder/initrd_builder.sh
- rootfs-builder/clearlinux/config.sh
- rootfs-builder/rootfs.sh
- scripts/lib.sh
- tests/image_creation.bats
Create a compressed YAML metadata file inside the rootfs image
containing information about the environment:
```
/var/lib/osbuilder/osbuilder.yaml.gz
```
Example contents:
```
---
osbuilder:
url: "https://github.com/kata-containers/osbuilder"
version: "unknown"
rootfs-creation-time: "2018-04-19T16:19:30.254610305+0000Z"
description: "osbuilder rootfs"
file-format-version: "0.0.1"
architecture: "x86_64"
base-distro:
name: "Centos"
version: "7"
packages:
- "iptables"
- "systemd"
agent:
url: "https://github.com/kata-containers/agent"
name: "kata-agent"
version: "0.0.1-2ec0b9593845b9a5e0eab5a85b20d74c35a2ca52-dirty"
agent-is-init-daemon: "no"
```
This change adds a new `-o` option to `rootfs.sh` for
specifying the version of osbuilder to the rootfs builder.
Fixes #35.
Signed-off-by: James O. …
> refactor and create a summary file inside the image

- README.md
Add a new Usage section with basic examples of how to run the builders from the `Makefile`.
Fixes #84.
> docs: Add a Usage section

- rootfs-builder/rootfs.sh
Current `rootfs.sh `fails when `GOPATH` is a set of directories.We
simply choose the first one as the working directory, as go get
only works against the first item in the `GOPATH`.
Signed-off-by: Penny Zheng <penny.zheng@arm.com>
> kata/osbuilder: Add support for multiple GOPATH directories

- rootfs-builder/rootfs.sh
For now, the flag "-a" or relevant shell variant "${AGENT_VERSION}" hasn't been used, only defined. Using 'git checkout' command to go into requested branch.
Fixes: #90
Signed-off-by: Penny Zheng <penny.zheng@arm.com>
> rootfs.sh: Add "${AGENT_VERSION}"/"-a" functionality

- scripts/lib.sh
Added the extra packages the user requested to the summary file as
previously only the default packages were listed.
Fixes #92.
> rootfs: Add extra packages to summary file

- rootfs-builder/rootfs.sh
Commit b8f1a688340c7b1cfe5a1cb1bbe6a792dc97acf8 ("rootfs: Simplify
code") introduced a variable called destdir but accidentally used
dest_dir with cp(1) instead.  This causes kernel modules to be copied to
the wrong location.
Rename the variable to dest_dir to be consistent with module_dir and
rootfs_dir variables used in this function.
Fixes: #94
> rootfs: copy kernel modules to correct location

- image-builder/README.md
- image-builder/image_builder.sh
- rootfs-builder/README.md
- tests/image_creation.bats
Building an image requires systemd to be installed in the rootfs as the
init daemon, so assert that systemd is available.
Fixes #98.
> Image require systemd

- .ci/setup.sh
- rootfs-builder/alpine/Dockerfile.in
- rootfs-builder/centos/Dockerfile.in
- rootfs-builder/clearlinux/Dockerfile.in
- rootfs-builder/euleros/Dockerfile.in
- rootfs-builder/fedora/Dockerfile.in
- rootfs-builder/rootfs.sh
- rootfs-builder/template/Dockerfile.template
Don't default to a hard-coded Intel architecture - default to the host
architecture.
Fixes #100.
> rootfs: Default to host architecture

- .ci/setup.sh
- tests/image_creation.bats
After building the images, perform a very basic test by configuring the runtime to use them and creating a container.
Also a number of cleanups.
Fixes #97.
> tests: Test generated images and initrd's (+ cleanups)

- .ci/lib.sh
- .ci/setup.sh
`.ci/setup.sh` is using dnf instead of yum to install
centos dependencies. This fixes it to use yum.
Fixes: #104.
Signed-off-by: Salvador Fuentes <salvador.fuentes@intel.com>
> CI: use yum for resolving centos dependencies

- rootfs-builder/rootfs.sh
shell usage function use wrong way to get AGENT_BIN value
Signed-off-by: Liu Changcheng <changcheng.liu@intel.com>
> rootfs: correct rootfs script deference var value

- image-builder/image_builder.sh
- rootfs-builder/rootfs.sh
If we set env USE_DOCKER true, we will use container to create rootfs.After docker run command, this temporary container would be no use. we could add -rm flag to automatically delete intermediate container.
Fixes: #115
Signed-off-by: Penny Zheng <penny.zheng@arm.com>
> rootfs: add '-rm' to delete intermediate container

- .ci/lib.sh
The `static-checks.sh` script now requires the repo as an argument.
Fixes #120.
> CI: Fix static-checks script invocation

- .ci/lib.sh
- .ci/run.sh
- .ci/setup.sh
- tests/image_creation.bats
- tests/image_creation.sh
The `kata-manger.sh` utility is changing its behaviour so that
`install-packages` *only* installs packages (no container manager).
Update the command to both install Docker and the packages.
Fixes #113.
> tests: Update kata-manager command

- image-builder/Dockerfile
- rootfs-builder/centos/Dockerfile.in
- rootfs-builder/clearlinux/Dockerfile.in
- rootfs-builder/euleros/Dockerfile.in
- rootfs-builder/fedora/Dockerfile.in
- rootfs-builder/rootfs.sh
proxy server must be specified in configuration file
of the package manager, /etc/yum.conf for yum or
/etc/dnf/dnf.conf for dnf
fixes #123
> builder: support proxy in distros based on yum or dnf

- image-builder/image_builder.sh
The image_builder.sh script must be run as root.  The following check is
performed before the script checks for root:
[ "${AGENT_INIT}" == "yes" ] || [ -x "${ROOTFS}/usr/bin/${AGENT_BIN}" ] || \
die "/usr/bin/${AGENT_BIN} is not installed in ${ROOTFS}
use AGENT_BIN env variable to change the expected agent binary name"
The -x test is "True if the file is executable by you".  It may evaluate
to true as root and false as non-root, depending on the file
permissions.
The permissions for kata-agent given in the Developer Guide are 0550
(https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md#add-a-custom-agent-to-the-image---optional).
Therefore image_builder.sh fails with "/usr/bin/${AGENT_BIN} is not
installed" when run as non-root.  This is confusing since the agent …
> image-builder: require root earlier for better error messages

- .ci/setup.sh
Fix CI build failures on Ubuntu 16.04 due to `make` not being installed.
Fixes #134.
> CI: Install make on Ubuntu

- rootfs-builder/rootfs.sh
Using docker we always add the go tarball. But this takes time if build image multiples times.
Use RUN to avoid duplicated steps already done in dockerfile.
Fixes: #125
Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>
> rootfs: docker: Reduce build time by not reinstalling go

- initrd-builder/initrd_builder.sh
If initrd_builder.sh fails partway through it may not be possible to run
it again without creating a new rootfs.
This happens because initrd_builder.sh checks for the presence of
/sbin/init and refuses to run if it is missing.  Later on, the script
moves /sbin/init to /init, where the kernel expects to find it in an
initramfs.  After this step initrd_builder.sh will refuse to run again
since /sbin/init is now missing.
Create a symlink from /init to /sbin/init instead of moving the file.
This allows initrd_builder.sh to be run repeatedly on the same rootfs.
Fixes: #130
> initrd-builder: make initrd_builder.sh idempotent

- rootfs-builder/rootfs.sh
Fail if we can not check out to the requested agent version.
Dont checkout to any branch by default.
> rootfs: Fail on non existing agent version.

- rootfs-builder/fedora/Dockerfile.in
- rootfs-builder/fedora/config.sh
Fedora 28 was released May 1st 2018.  I have tested that the rootfs
works.
Fixes: #132
> rootfs-fedora: bump Fedora release to 28

- rootfs-builder/alpine/Dockerfile.in
- rootfs-builder/centos/Dockerfile.in
- rootfs-builder/clearlinux/Dockerfile.in
- rootfs-builder/fedora/Dockerfile.in
Ensure the image used on the guest does include libseccomp,
otherwise when a seccomp profile is passed by the runtime, it
will end up with boot failure on the guest.
Fixes: #153
Signed-off-by: Nitesh Konkar niteshkonkar@in.ibm.com
> rootfs: Include libseccomp support in rootfs

- Makefile
- README.md
Update Makefile so that build artifacts are actually tracked as make targets. This is to enforce a strict prerequisite ordering and better handle parallel builds.
Fixes: #157
> Makefile: update targets to better track build artifacts

- .ci/setup.sh
- tests/test_images.sh
At the end of the tests, show a summary of the sizes of all the images
and initrds along with their sizes.
Fixes #162.
> tests: Show summary of image sizes

- tests/test_images.sh
Remove the redundant `--distro` argument; when needed, the distro can be
specified using a positional argument.
Fixes: #158
> osbuilder: Remove redundant argument to test_image.sh

- tests/test_images.sh
Reformat the usage output displayed with `help` command or `-h` option.
Trap exit codes only after options parsing, as that is used to generate a test report.
Before:
```
Usage: test_images.sh [help|<distro>]                                                                                  
test_images.sh [options]                                                                                        
Options:                                                                                                               
-h | --help          # Show usage.                                                                                   
--distro <distro>    # Only run tests for specified distro.                                                          
--list               # List all distros …
```
> Reformat usage output in test_image.sh

- .travis.yml
- Makefile
- rootfs-builder/rootfs.sh
- tests/test_config.sh
- tests/test_images.sh
Rework test_image.sh and Makefile to allow building images in parallel
for faster test execution.
Add some new targets to Makefile ({rootfs,image,initrd}-all,
list-distros).
Fixes: #168
> tests: parallel images build support

- tests/test_images.sh
Detect when dockerd config is sourced from a sysconfig file instead of
being hardcoded in the systemd unit file, and improve re matching for the
two cases.
Fixes: #180
> tests: handle docker set runtime for systemd / sysconfig

- README.md
- rootfs-builder/rootfs.sh
- rootfs-builder/suse/Dockerfile.in
- rootfs-builder/suse/config.sh
- rootfs-builder/suse/config.xml
- rootfs-builder/suse/install-packages.sh
- rootfs-builder/suse/rootfs_lib.sh
- tests/test_config.sh
> Add support for suse rootfs

- Makefile
- rootfs-builder/alpine/config.sh
- rootfs-builder/centos/config.sh
- rootfs-builder/clearlinux/config.sh
- rootfs-builder/debian/config.sh
- rootfs-builder/euleros/config.sh
- rootfs-builder/fedora/config.sh
- rootfs-builder/rootfs.sh
- rootfs-builder/suse/config.sh
- rootfs-builder/template/config_template.sh
- rootfs-builder/ubuntu/config.sh
- tests/test_config.sh
- tests/test_images.sh
Move the test configuration in the distro-specific config.sh
file, for better control of what to include/exclude from
testing based on the test environment.
test_config.sh is still used to exclude specific distros from
being tested, when running tests in bulk.
Fixes: #182
> tests: get config from distro-specific config.sh

- image-builder/README.md
Correct rootfs builder link in the image builder README.
Fixes #185.
Signed-off-by: Yonatan Gefen yoni.gefen@gmail.com
> docs: Fix link in README

- rootfs-builder/euleros/config.sh
- rootfs-builder/rootfs.sh
- rootfs-builder/template/config_template.sh
- tests/test_config.sh
- tests/test_images.sh
When running test_images.sh, allow specific rootfs builds to
fail without impacting the overall tests results.
The distros allowed to fail are the ones specifying
BUILD_CAN_FAIL in their config.sh.
> tests: allow rootfs build to fail for specific distros

- rootfs-builder/rootfs.sh
This patch added -x option to curl: -x uses the http_proxy
settings to download golang binary behind the firewall
Signed-off-by: Leno Hou <lenohou@gmail.com>
> rootfs.sh: enable curl use http_proxy

- .ci/run.sh
- rootfs-builder/alpine/config.sh
- rootfs-builder/centos/config.sh
- rootfs-builder/clearlinux/config.sh
- rootfs-builder/euleros/config.sh
- rootfs-builder/fedora/config.sh
- rootfs-builder/rootfs.sh
- rootfs-builder/ubuntu/config.sh
If the rootfs is built with SECCOMP=yes environment
variable then include libseccomp package inside the
rootfs image. Else do not include it.
Fixes: #155
Signed-off-by: Nitesh Konkar niteshkonkar@in.ibm.com
> rootfs: Conditionally add libseccomp support in rootfs image

- tests/README.md
- tests/test_images.sh
Skip installation of docker and kata packages when the environment
variable KATA_DEV_MODE is not empty, as a dev system may be using
a non standard setup.
Fixes: #195
> tests: skip docker,kata install with KATA_DEV_MODE

- Makefile
- rootfs-builder/rootfs.sh
- scripts/lib.sh
Allow install osbuilder scripts in a host, packages like 
https://bugzilla.redhat.com/show_bug.cgi?id=1590414 may install them in the host.
> Add 'install' target to makefile

- README.md
- rootfs-builder/suse/config.sh
Fix port URL detection for aarch64, and error out if an unknown
architecture is detected.
Fixes: #215
>  suse: fix port URL detection for aarch64

- .ci/setup.sh
We require make and gcc to run our CI tools.
Fixes: #219.
Signed-off-by: Salvador Fuentes <salvador.fuentes@intel.com>
> setup: Add make and gcc as dependencies

- image-builder/image_builder.sh
- rootfs-builder/alpine/Dockerfile.in
- rootfs-builder/rootfs.sh
- rootfs-builder/ubuntu/config.sh
The `arch(1)` command is not available on some systems so use the
`uname(1)` command for the equivalent functionality.
Fixes #150.
> arch: Remove calls to arch command

- tests/test_config.sh
- tests/test_images.sh
euleros mirrors are down almost all time, don't fail if euleros rootfs
or image can't be generated.
fixes #238
> tests: skip euleros

- .gitignore
- Makefile
- image-builder/Dockerfile
- image-builder/image_builder.sh
- image-builder/nsdax.gpl.c
- rootfs-builder/rootfs.sh
The new NVDIMM driver implementation (kernel >= 4.16) needs to know the device
namespace information to map pages, this metadata is read from the nvdimm
namespace at 4k offset.
fixes #235
> image-builder: fill out device namespace information into kata image

- image-builder/image_builder.sh
- tests/test_images.sh
Not all hypervisor support NVDIMM hence DAX support MUST BE enabled explicitly
setting the DAX environment variable to 'yes'
fixes #246
> image-builder: make DAX support optional

- image-builder/image_builder.sh
With the old code it was possible to see odd messages like:
"INFO: Create root disk image. Attempt 6 out of 5."
Move the attempt number print to after we check against the max
> Print attempt number after max check

- rootfs-builder/centos/Dockerfile.in
- rootfs-builder/centos/config.sh
- rootfs-builder/clearlinux/Dockerfile.in
- rootfs-builder/clearlinux/config.sh
- rootfs-builder/debian/Dockerfile.in
- rootfs-builder/debian/config.sh
- rootfs-builder/euleros/Dockerfile.in
- rootfs-builder/euleros/config.sh
- rootfs-builder/fedora/Dockerfile.in
- rootfs-builder/fedora/config.sh
- rootfs-builder/rootfs.sh
- rootfs-builder/ubuntu/Dockerfile.in
- rootfs-builder/ubuntu/config.sh
chrony will be used to schronize guest clock with host
using kvm_ptp kernel driver.
This does add another active component to the rootfs
but keeping time scychorized is crucial.
Fixes #255
> Add chrony to image

- image-builder/image_builder.sh
- rootfs-builder/rootfs.sh
When using docker, pass the `DEBUG` flag to trace the commands as well.
Signed-off-by: Li Yuxuan <liyuxuan04@baidu.com>
> builder: Pass the DEBUG flag when using docker

- image-builder/Dockerfile
- image-builder/image_builder.sh
- scripts/lib.sh
- tests/test_images.sh
Re-implement image builder script to generate an image with a double MBR +
a DAX metadata. The DAX metadata is read by the NVDIMM driver to know the
beginning of the data in the pmem device.
This new image format is required to enable DAX in the kernels and hypervisors
that support NVDIMM, without breaking the compatibility with the kernels and
hypervisors that don't support it.
Following diagram shows how the resulting image will look like
```
.-----------.----------.---------------.-----------.
| 0 - 512 B | 4 - 8 Kb |  2M - 2M+512B |    3M     |
|-----------+----------+---------------+-----------+
|   MBR #1  |   DAX    |    MBR #2     |  Rootfs   |
'-----------'----------'---------------'-----------+
|          |      ^      |        ^
|          '-data-'      '--------'
| …
```
> image-builder: re-implement image builder script

- rootfs-builder/rootfs.sh
On some systems the "runc" runtime isn't available or has a different
name.  Allow the user to override the Docker runtime.
Fixes: #268
> rootfs-builder: add rootfs.sh DOCKER_RUNTIME env var

- image-builder/image_builder.sh
Share with the container the mkfs configuration file to use only the
filesystem features supported in the host.
fixes #270
cc @GabyCT @jcvenegas @marcov  @jodh-intel 
> image-builder: share the mkfs configuration file

- rootfs-builder/rootfs.sh
/var/log is not required in the rootfs
fixes #254
> rootfs-builder: remove /var/log

- Makefile
- image-builder/image_builder.sh
- make: add nsdax source to install-scripts target (nsdax.gpl.c is required by image_builder.sh).  Fixes: #283
- image-builder: set default value of AGENT_INIT
> make: add nsdax source to install-scripts target

- rootfs-builder/rootfs.sh
Replace "which" with "command", that's a bash built-in and should
not generate any stderr messages. This also fixex the spurious creating
of "1" file in the repo root because of a typo in stderr redirect.
Fixes: #286
Signed-off-by: Marco Vedovati <mvedovati@suse.com>
> rootfs: use command vs which, avoid "1" file creation

- image-builder/Dockerfile
- image-builder/image_builder.sh
Remove systemd units and files that are not needed in Kata Containers.
Removing this files we can improve the boot time.
fixes #289
`before` = with all systemd files and units
`after` = without unneeded systemd files and units (this patch)
cc @grahamwhaley @jodh-intel @bergwolf 
> image-builder/boot time: remove unneeded systemd units and files

- rootfs-builder/alpine/Dockerfile.in
Remove the version of alpine used when pulling golang docker images. This ensures the latest version of alpine is used and resolves the maintenance issue when old versions of alpine are dropped.
Fixes: #293.
> rootfs: Don't hardcode alpine version for golang images

- rootfs-builder/rootfs.sh
Chrony service is not started because it requires a private temporal directory,
these directories can't be created in read-only filesystems. Create a symlink
to /tmp in /var allowing systemd to create private temporal directories.
fixes #280
> rootfs-builder: fix chrony service

- image-builder/image_builder.sh
systemd complains if `/etc/machine-id` does not exist. Create the `machine-id`
file to make systemd happy, it'll bind-mount that file to write the machine id.
fixes #296
fixes github.com/kata-containers/runtime#1537
> image-builder: create /etc/machine-id

- image-builder/image_builder.sh
We should start this unit so that systemd can mount /tmp as
tmpfs.
Fixes #300
> tmp: Do not remove tmp.mount unit file from the rootfs

- rootfs-builder/clearlinux/config.sh
This package contains mount command among several other commands.
Unlike other distros, this package is not auto-pulled with systemd.
Add this package explicitly.
Fixes #302
> clear: Add util-linux-bin package to Clearlinux rootfs

- rootfs-builder/rootfs.sh
- rootfs-builder/ubuntu/rootfs_lib.sh
~~On Debian / Ubuntu, tmp.mount is not installed in
/[etc|usr/lib]/systemd/system by default, but in
/usr/shared/systemd, and need to be manually copied there
to have /tmp mounted as tmpfs.~~
On some distros (Debian, Ubuntu, openSUSE), tmp.mount is not
installed by default in /[etc|usr/lib]/systemd/system, but
just in /usr/shared/systemd, so it needs to be manually copied
there to have /tmp mounted as tmpfs.
Fixes: #317
Signed-off-by: Marco Vedovati <mvedovati@suse.com>
> rootfs: install systemd tmp.mount if needed

- rootfs-builder/rootfs.sh
Hypercall to implement virtual PTP was introduced in kernel 4.10
Have chrony run only if the device created by kvm-ptp exists.
Add this as a ConditionExists in the systemd service file.
This service if named as chrony.service in deb based distributions
rather than chronyd.service, although a systemd alias exists.
However it is not possible to come up with a generic `PATH` systemd
unit relying on the alias.
> chrony: Configure chrony to start only when /dev/ptp0 exists.

- .ci/run.sh
- Makefile
- tests/test_images.sh
Reduce the amount of logs displayed when running test. This is achieved
calling commands using chronic, and printing extra information about
the Kata / Docker configuration only if a test fails to start a
container.
Fixes: #145
---- 
| | Log Lines<br>(with no failures)|mfw|
|-|--------|---|
|w/o this PR|14695|🙀|
|with this PR|321|😺|
> tests: reduce the amount of log displayed

- rootfs-builder/clearlinux/config.sh
- rootfs-builder/euleros/config.sh
For clearlinux, for now, it is only designed for amd64.
For euleros, it has supported aarch64 starting from 2.3, but here is the sad part. 
there existed bugs in their 2.3.x image, this bug existed in both x86_64 and aarch64 image. related issue [euleros/euleros-docker-images/#13](https://github.com/euleros/euleros-docker-images/issues/13) has been raised.
since x86_64 is using version 2.2, it's fine there, stay on that.😎
> rootfs-builder: exclude unsupported archs from euleros and clearlinux

- rootfs-builder/rootfs.sh
The current chrony service does not step the system clock,
so add the modification to do this if the adjustment is
larger than one second
Fixes: #316
Signed-off-by: Yang, Wei <wei.yang1@linux.alibaba.com>
> rootfs: configure chronyc service with makestep

- rootfs-builder/rootfs.sh
We are seeing sporadic failures in the rootfs creation as listed here:
https://github.com/kata-containers/tests/issues/1744
While this cannot be reproduced locally, there is no reason
for the failure to write to $ROOTFS_DIR/etc/chrony.conf unless the upper
directories are missing as this file should be created if it did not
exist earier.
So just create the etc directory to test out if we see these sporadic
failures in the CI.
Fixes #328
> rootfs: Make sure etc exists.

- rootfs-builder/clearlinux/Dockerfile.in
- rootfs-builder/fedora/Dockerfile.in
- rootfs-builder/fedora/config.sh
Use fedora 30 in docker images.
Fixes: #331
> rootfs: upgrade docker images for fedora

- image-builder/image_builder.sh
The available directory size  calculated as Gb while creating a bigger custom image.  
This little fix makes it comparable  with `${rootfs_size_mb}` and tested to be useful.
Signed-off-by: ClarkLee <clarklee1992@hotmail.com>
> image-builder: get mount directory size with Mb format

- scripts/lib.sh
Allow to override build date with `SOURCE_DATE_EPOCH`
in order to make builds reproducible.
See https://reproducible-builds.org/ for why this is good
and https://reproducible-builds.org/specs/source-date-epoch/
for the definition of this variable.
Also use UTC to be independent of timezone.
Note: This date call only works with GNU date.
Without this patch, `kata-containers-initrd.img` contained a varying `var/lib/osbuilder/osbuilder.yaml` with
```diff
osbuilder:
url: "https://github.com/kata-containers/osbuilder"
version: "1.9.0-alpha0"
-rootfs-creation-time: "2019-08-06T18:40:27.402493939+0000Z"
+rootfs-creation-time: "2034-09-08T07:57:34.386990704+0000Z"
```
This PR was done while working on reproducible builds for openSUSE.
> Allow to override build date with SOURCE_DATE_EPOCH

- image-builder/image_builder.sh
Since the image rootfs is readonly, we
create an empty /etc/resolv.conf which
the agent would later bind-remount as
read-write.
Fixes: #345
> image_builder: create /etc/resolv.conf

- Makefile
dracut will process conf files with bash, and in fact it's common to use idioms like += in conf files for string concatenation. The current grep usage in the Makefile won't catch all possible valid 'drivers'
variable cases.
Instead, use bash to parse and echo the 'drivers' content
Fixes: #356
> make: use bash to fetch dracut conf 'drivers' list

- rootfs-builder/fedora/config_aarch64.sh
there is issue in fedora:28 when start systemd service.
update fedora to 29 will bypass this issue.
Fixes: #349
Signed-off-by: Jianyong Wu <jianyong.wu@arm.com>
@devimc @marcov @jcvenegas
> rootfs: update fedora to 29 for arm64.

- image-builder/image_builder.sh
- rootfs-builder/rootfs.sh
Create an empty /etc/resolv.conf in initrd rootfs
so that the agent can bind mount it for DNS in
kata VM.
Fixes: #365
> initrd_builder: Create empty resolv.conf in rootfs

- README.md
Update osbuilder README to use DEBUG
environment variable for executing scripts in
debug mode.
Fixes:  #368
> README: Update how to use DEBUG variable

- README.md
- image-builder/Dockerfile
- image-builder/image_builder.sh
- rootfs-builder/alpine/Dockerfile.in
- rootfs-builder/centos/Dockerfile.in
- rootfs-builder/clearlinux/Dockerfile.in
- rootfs-builder/debian/Dockerfile.in
- rootfs-builder/euleros/Dockerfile.in
- rootfs-builder/fedora/Dockerfile.in
- rootfs-builder/rootfs.sh
- rootfs-builder/suse/Dockerfile.in
- rootfs-builder/ubuntu/Dockerfile.in
In case a user wants to use podman instead of
docker to build initrd/rootfs images, facilitate
it by setting the variable `USE_PODMAN=true`.
Fixes: #370
> osbuilder: Add USE_PODMAN as an alternate for USE_DOCKER

- rootfs-builder/alpine/config.sh
use latest stable to fix CVEs
fixes #379
> rootfs-builder/alpine: use latest stable

- Makefile
Due to the option '--directory' just added from 'cpio' v2.12, so the
osbuilder will failed with old version 'cpio' before v2.12, such as in
Centos 7 with v2.11.
Fix it by replacing this option with '(cd ...; cat ...)'.
Fixes: #384
Signed-off-by: Shile Zhang <shile.zhang@linux.alibaba.com>
> make: use `cd` instead of '--directory' option of `cpio`

- image-builder/image_builder.sh
Leaving nsdax behind may create some isses for the distro packages
of kata-osbuilder, as every package would have to take care of purging
the file on each distro.
Knowing that, we better remove the file as part of the script, mainly
because the file is already regenerated everytime in any case.
Fixes: #394
Signed-off-by: Fabiano Fidêncio <fidencio@redhat.com>
> image_builder: Remove nsdax binary after its usage

- image-builder/image_builder.sh
Add DOCKER_RUNTIME variable to change container runtime depending on the
CI/environment.
fixes #397
> image-builder: make docker runtime configurable

- .ci/run.sh
- .travis.yml
- dracut/Dockerfile.in
- rootfs-builder/alpine/Dockerfile.in
- rootfs-builder/centos/Dockerfile.in
- rootfs-builder/clearlinux/Dockerfile.in
- rootfs-builder/debian/Dockerfile.in
- rootfs-builder/euleros/Dockerfile.in
- rootfs-builder/fedora/Dockerfile.in
- rootfs-builder/rootfs.sh
- rootfs-builder/suse/Dockerfile.in
- rootfs-builder/suse/install-packages.sh
- rootfs-builder/ubuntu/Dockerfile.in
- scripts/lib.sh
- tests/test_config.sh
- tests/test_images.sh
Build rust agent and go agent using the same rootfs bulder image.
When building rust agent, just add RUST_AGENT=yes before command line.
The documentation will be updated later
Enhancement: #360
Signed-off-by: Yang Bo <bo@hyper.sh>
> Rootfs builder: build rust agent using osbuilder

- tests/README.md
- tests/test_images.sh
This series adds improvements for running test_images.sh locally
* KATA_DEV_MODE now really doesn't touch any host config. Users are
required to put the host into the proper state first, namely not
having kata-runtime as the default runtime. Running the script
this way is effectively a build test only, because we don't have
any way to runtime test the generated initrd/images without altering
host config. Still, the build step is 80% of the battle IMO
* Improvements to not have the dracut build process leave output lying
around in the osbuilder.git project dir
* Debugging improvements, have DEBUG=1 make the script output much
more info.
* Some code cleanups and dead code removal
Fixes: #415
> tests: Improve running test_images.sh locally

- rootfs-builder/rootfs.sh
The prepare_overlay() code path is called when rootfs.sh is invoked
with no passed in distro string. This is used for the dracut case
from the Makefile for example. In that particular case, the starting
root directory is empty.
It's also valid to pass a prepopulated directory to rootfs.sh, which
is essentially a request for the script to just make the necessary
kata changes. Currently though prepare_overlay() makes some changes
that could wipe out pre-arranged /sbin/init setup.
Check first to see if /sbin/init exists in the rootfs dir, and if so,
skip the symlink changes
Fixes: #419
> rootfs: Don't overwrite /sbin/init if it already exists

- rootfs-builder/debian/Dockerfile-aarch64.in
- rootfs-builder/rootfs.sh
- rootfs-builder/ubuntu/Dockerfile-aarch64.in
- scripts/lib.sh
Hi~ guys 
I've been trying to build rust-agent image on AArch64 for a couple days. ;)
The existing method needs a few refinement to work it out. 
- **Install musl on aarch64**
The original musl-installing method is only for `x86_64` and `i386`.
[musl.cc](https://musl.cc/) provides small and reliable pre-built musl tool-chains for many architectures.
Static so they run on supported platforms without dependencies.
- **ubuntu/debian: create aarch64-specific Dockerfile.in**
The musl package in ubuntu/debian(`musl`, `musl-dev`, `musl-tools`) could not provide everything we need on aarch64. 
e.g. we need `aarch64-linux-musl-gcc` as linker, and it's not provided in package.
So I'll use above static tool chains to replace them.
- **rootfs: remove RUST_SRC_PATH** 
If user wants to use customized …
> AArch64: Build rust image on aarch64

- scripts/lib.sh
Use the path where `install-yq.sh` installs `yq` as the default path to the
`yq` binary in `lib.sh`.
Install `yq` in the default path if it doesn't exist.
fixes #429
> scripts: set a default path to the yq binary

- rootfs-builder/debian/Dockerfile.in
- rootfs-builder/ubuntu/Dockerfile.in
By default, Ubuntu or Debian based "apt" or "apt-get" system installs recommended but not suggested packages .
By passing "--no-install-recommends" option, the user lets apt-get know not to consider recommended packages as a dependency to install.
This results in smaller downloads and installation of packages .
Refer to blog at [Ubuntu Blog](https://ubuntu.com/blog/we-reduced-our-docker-images-by-60-with-no-install-recommends) .
Fixes : #427 
Signed-off-by: Pratik Raj <rajpratik71@gmail.com>
> pod : optimization Some debian package manager tweaks

- image-builder/image_builder.sh
Immutable systems, as such Red Hat Core OS and Fedora Core OS, will not
allow mount_dir to be created in a location that's not read-write.
Let's ensure we use /tmp as base for mount_dir, as it's a safe writable
choice for any distro supported by kata.
Fixes: #437 
Signed-off-by: Fabiano Fidêncio <fidencio@redhat.com>
> image_builder: Force mount_dir to be created in /tmp

- scripts/lib.sh
Need to verify that rust deps are available on s390x
Fixes #438
Signed-off-by: Alice Frosi <afrosi@de.ibm.com>
> s390x: Skip rust for s390x

- initrd-builder/initrd_builder.sh
Nothing inherently requires root here. If the ROOTFS_DIR is only
root accessible then the operation may fail, but better IMO to let
that fail naturally
Fixes: #422
> initrd-builder: Don't error if run as non-root

- image-builder/image_builder.sh
Qemu merely limits the memory-backend-file size to be aligned to page_size
instead of section size(arm64 1GB). Please see file_ram_alloc() in qemu
exec.c. If we use 1024MB, the generated image size will be 3-4 times bigger
than the original one.
After relaxing it, the image size will be changed from 1G to 300M+ on arm64
with Fedora 29 rootfs's default configuration.
I do see there are some different limitation for ram_block on other arches
(e.g. s390x). So gracefully keep other arches unchanged here.
Fixes #404
Signed-off-by: Jia He <justin.he@arm.com>
> image_builder: Reduce the boundary mb for reducing image size on arm64

- tests/test_images.sh
**Which feature do you think can be improved?**
When debugging ARM CI failure in https://github.com/kata-containers/ci/issues/268, I found tons of stale test results under `/tmp`, which were traced back to here [osbuilder/tests/test_images.sh](https://github.com/kata-containers/osbuilder/blob/master/tests/test_images.sh#L15)
```
root@arm-testing-2:~# du -k --max-depth=1 /tmp | grep "osbuilder-test"
36      /tmp/osbuilder-test.6On2ZYj
1209852 /tmp/osbuilder-test.mdWy5TB
1174800 /tmp/osbuilder-test.yH3xtJI
1174780 /tmp/osbuilder-test.HNgoRc1
1209860 /tmp/osbuilder-test.aBtTRjD
1174788 /tmp/osbuilder-test.jOmHsag
1209868 /tmp/osbuilder-test.GdEFsPu
1209860 /tmp/osbuilder-test.g7IBuy1
1051776 /tmp/osbuilder-test.TS7agUD
673268  /tmp/osbuilder-test.8OFe9vA
1209868 /tmp/osbuilder-test.7KP8xJ1 …
```
> tests: deleting stale test results when tests failed

- rootfs-builder/debian/Dockerfile-aarch64.in
- rootfs-builder/debian/Dockerfile.in
- rootfs-builder/ubuntu/Dockerfile-aarch64.in
- rootfs-builder/ubuntu/Dockerfile.in
- scripts/lib.sh
Now, ARM CI failed on the following errors:
https://github.com/kata-containers/ci/issues/276
```
05:09:13 Setting up tzdata (2019c-3ubuntu1) ...
05:09:13 debconf: unable to initialize frontend: Dialog
05:09:13 debconf: (TERM is not set, so the dialog frontend is not usable.)
05:09:13 debconf: falling back to frontend: Readline
05:09:13 Configuring tzdata
05:09:13 ------------------
05:09:13 
05:09:13 Please select the geographic area in which you live. Subsequent configuration
05:09:13 questions will narrow this down by presenting a list of cities, representing
05:09:13 the time zones in which they are located.
05:09:13 
05:09:13   1. Africa      4. Australia  7. Atlantic  10. Pacific  13. Etc
05:09:13   2. America     5. Arctic     8. Europe    11. SystemV
05:09:13   3. Antarctica  6. …
```
> rootfs-builder: add DEBIAN_FRONTEND=noninteractive

- README.md
- dockerfiles/QAT/Dockerfile
- dockerfiles/QAT/README.md
- dockerfiles/QAT/qat.conf
- dockerfiles/QAT/run.sh
Add a method to automatically build a modified kernel and rootfs
to support QAT.
Given we don't generally have either:
- a fully enabled ('full fat') kernel for Kata, as it would be
big and slow
- kernel and rootfs variants, as that would seriously bloat our
test matrix and CI requirements, which would likely lead to more
strange and hard to find bugs....
maybe we can build a collection of 'helpers' to make building and
customizing a rootfs and kernel easier.
Fixes: #440
Signed-off-by: Graham Whaley <graham.whaley@intel.com>
> dockerfile: QAT: Add an automated QAT kernel/rootfs builder

- image-builder/image_builder.sh
Disable reflink when using DAX. Reflink is a xfs feature that cannot be
used together with DAX.
fixes #455
> image-builder: disable reflink

- image-builder/image_builder.sh
Disable reflink when using DAX. Reflink is a xfs feature that cannot be
used together with DAX.
fixes #455
> [backport-1.11] image-builder: disable reflink

- image-builder/image_builder.sh
Disable reflink when using DAX. Reflink is a xfs feature that cannot be
used together with DAX.
fixes #455
> [backport-1.10] image-builder: disable reflink

- rootfs-builder/rootfs.sh
Don't modify /sbin/init on the build host when using command `AGENT_INIT="yes" ./rootfs.sh centos` to build rootfs.
Fixes: #472
Signed-off-by: liangxianlong <liang.xianlong@zte.com.cn>
> rootfs-builder: Don't modify /sbin/init on the build host

- image-builder/image_builder.sh
- rootfs-builder/rootfs.sh
Fix a problem caused by the fact that on Fedora - but also Debian,
Ubuntu and most likely others, /lib and /sbin aren't directories but
symlinks to /usr/lib and /usr/sbin, respectively.  So when the commands
ln -sf  ../../init ./lib/systemd/systemd
ln -sf  ../init ./sbin/init
with relative targets meant to mean /init are executed on such distros,
the link name ./lib/systemd/systemd actually becomes
./usr/lib/systemd/systemd, ./sbin/init becomes ./usr/sbin/init and their
target turns out to be /usr/init which means that they dangle.
What's more, that the symlink created by the former 'ln' command
actually ends up at /usr/lib/systemd/systemd means that this dangling
link overwrites the actual systemd binary later on when dracut applies
this overlay to its tree.  This makes the initramfs …
> rootf-builder: fix unbootable dracut-based initramfs on Fedora

- image-builder/image_builder.sh
As it turns out, there probably isn't any single path where a systemd binary
is guaranteed to be found on any distro.  For this reason, allow for checking
multiple candidate locations.
Fixes #493
Signed-off-by: Pavel Mores <pmores@redhat.com>
> osbuilder: allow for checking multiple systemd paths verifying rootfs

- rootfs-builder/centos/config_aarch64.sh
- rootfs-builder/centos/config_ppc64le.sh
The key path of centos has removed from mirrors
Fixes #482
Signed-off-by: choury <chouryzhou@tencent.com>
> rootfs-builder: update centos arch key path

- rootfs-builder/rootfs.sh
- scripts/lib.sh
For the docker build of the rootfs based on golang agent,
we still end up installing these packages. Skip these.
Fixes #507
> rootfs: Skip installing cargo and rust for docker build

- rootfs-builder/rootfs.sh
- rootfs-builder/template/rootfs_lib_template.sh
- scripts/lib.sh
For the docker build of the rootfs based on golang agent,
we still end up installing these packages. Skip these.
Fixes #507
(cherry picked from commit b937cf70342a1dbf14e7e145f5083c9c10a63584)
> backport: rootfs: Skip installing cargo and rust for docker build

- rootfs-builder/ubuntu/rootfs_lib.sh
Improve Kata Containers memory footprint by reducing debian
image size.
Without this change:
Debian image -> 256MB
With this change:
Debian image -> 128MB
Note: this change *will not* impact significantly ubuntu's image size.
fixes #505
> rootfs: reduce size of debian image
