kata-containers/osbuilder

.pullapprove.yml
CODE_OF_CONDUCT.md

* Add the OpenStack Foundation CoC
* Add pullapprove support

Code Of Conduct and pullapprove support

---

.ci/run.sh
.ci/setup.sh
.travis.yml
image-builder/Dockerfile
image-builder/image_builder.sh
rootfs-builder/rootfs.sh
tests/image_creation.bats

Add a few tests to be run by travis.
Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>

ci: Add travis basic testing

---

README.md

Fixes:#54.
Signed-off-by: Liang Chenye <liangchenye@huawei.com>

add travis build status to README.md

---

rootfs-builder/template/Makefile

Fixes #67.
Signed-off-by: Nirmoy Das <ndas@suse.de>

makefile: fix makefile to find Dockerfile.template

---

rootfs-builder/rootfs.sh

Pass EXTRA_PKGS var to docker to build rootfs

---

image-builder/image_builder.sh

image-builder: fix "paratition" typo

---

README.md

Update README: Fix a minor space issue

---

VERSION

# Kata Containers 1.1.0

---

README.md

docs: Add Platform-Compatibility matrix

---

.travis.yml
rootfs-builder/centos/config_ppc64le.sh
tests/image_creation.sh

travis: Enable travis ci for ppc64le

---

rootfs-builder/rootfs.sh

rootfs.sh: Add Platform-OS matrix to help page

---

rootfs-builder/rootfs.sh
rootfs-builder/ubuntu/Dockerfile.in
rootfs-builder/ubuntu/config.sh
rootfs-builder/ubuntu/rootfs_lib.sh
tests/test_images.sh

Fixes #32 #141
Signed-off-by: Yash Jain <ydjainopensource@gmail.com>

OSbuilder : Add support for Ubuntu rootfs

---

rootfs-builder/rootfs.sh
rootfs-builder/ubuntu/config.sh

This PR adds s390x architecture.
Co-authored-by: Yash D Jain <ydjainopensource@gmail.com>
Signed-off-by: Alice Frosi <afrosi@de.ibm.com>

Add s390x architecture

---

rootfs-builder/rootfs.sh

Fixes: #217
Signed-off-by: Alice Frosi <afrosi@de.ibm.com>

s390x: set CC for fedora

---

README.md

Add s390 architecture to the compatibility matrix

docs: update compatibility matrix with s390

---

image-builder/image_builder.sh

As runtime/#624(https://github.com/kata-containers/runtime/pull/624#discussion_r212534586) discussed before, the size of memory section is arch-dependent.
For arm64, it should be 1G, not 128MB.
Fixes: #224
Signed-Off-By: Penny Zheng <penny.zheng@arm.com>

memory_hotplug: MEM_BOUNDARY_MB should be arch-dependent

---

tests/test_images.sh

install kata containers components from master and run osbuilder tests
fixes #242

tests: install kata components from master

---

tests/test_images.sh

We need to modify this test in order to handle firecracker.
Fixes #248
Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

test: Modify test_images script to handle FC

---

image-builder/image_builder.sh

Add filesystem type to format the loop device.
fixes #270

image-builder: add fs type

---

rootfs-builder/rootfs.sh

rootfs.sh fails on machines with SELinux in enforcing mode if the
volumes aren't labelled.
This patch labels volumes so the container is able to access them.
In order to do this rootfs directory creation must be moved before the
Docker container is started.  Previously docker-run(1) would create the
rootfs directory in the USE_DOCKER case.
Fixes: #266

rootfs-builder: SELinux relabel container volumes

---

rootfs-builder/README.md

Resolve issues with markdown in this repo.
Fixes #278.

docs: Fix markdown

---

CODE_OF_CONDUCT.md
README.md
rootfs-builder/README.md

Correct spelling mistakes and resolve formatting issues.
Fixes: #298.

docs: Fix spelling and formatting

---

tests/README.md

Correct a spelling mistake.
Fixes: #309.

docs: Fix typo

---

rootfs-builder/rootfs.sh

When the rootfs creation is used for PRs there is
not a match with a kata runtime version, in this
case lets clone the runtime repository and checkout
to the kata branch target. If is already cloned
this mean this was set by depens-on script or the user.
Fixes: #326
Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>

rootfs: fix golang version detection

---

rootfs-builder/rootfs.sh

commit 39370c2 has accidentally deleted the content in #265
Here, I just re-patch PR#265 on the latest master code.
Fixes: #338
Signed-off-by: Penny Zheng <penny.zheng@arm.com>

chrony-service: re-patch PR#265

---

image-builder/image_builder.sh

kata-agent is moved to /sbin/init when AGENT_INIT is yes. Check
/sbin/init exists and it's not systemd
fixes #322

image-builder: check /sbin/init when AGENT_INIT=yes

---

rootfs-builder/rootfs.sh

Detecting the host distro allows the rootfs setup to be correctly
carried out.
Fixes: #343
Signed-off-by: Marco Vedovati <mvedovati@suse.com>

dracut: improve host distro support

---

rootfs-builder/clearlinux/config.sh
rootfs-builder/debian/config.sh
rootfs-builder/ubuntu/config.sh

Add kmod package for loading kernel modules

Add kmod package

---

image-builder/image_builder.sh

In Fedora we are running the osbuilder scripts on the client machine,
to generate an initrd for the running host kernel. In this setup,
there's currently a runtime dependency on gcc for compiling the nsdax
tool, which is suboptimal.
Add NSDAX_BIN environment variable; if specified, image-builder.sh
will use that path as the nsdax tool. This let's ship a compiled
nsdax tool to users and drop the runtime gcc dependency
Fixes: #417

image-builder: Add NSDAX_BIN for passing in compiled nsdax tool

---

scripts/install-yq.sh
scripts/lib.sh

This PR will update yq version to 3.1.0 in order to match with other
kata repositories.
Fixes #421
Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

scripts: Update yq

---

rootfs-builder/gentoo/rootfs_lib.sh

Quote conflicting packages and fix use of `-Wl-z`
fixes #503

rootfs: gentoo: fix rootfs image build
